# Generated by Django 5.2.1 on 2025-05-13 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tarefa",
            name="data_hora",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
